# .streamlit/config.toml
# Professional Trading Dashboard Theme Configuration

[theme]
# Primary color - Used for interactive elements, links, and highlights
primaryColor = "#4facfe"

# Background color - Main app background
backgroundColor = "#f8f9fa"

# Secondary background color - Sidebar and secondary elements
secondaryBackgroundColor = "#e9ecef"

# Text color - Main text color
textColor = "#2c3e50"

# Font family - Professional fonts
font = "sans serif"

[server]
# Server configuration for better performance
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false
showErrorDetails = false

[client]
# Client configuration for better UX
showErrorDetails = false
toolbarMode = "minimal"