ALPHA_VANTAGE = "5Q1OGRF9STMR8E6M"
POLYGON = "Q_tpbILBBIG0LxmeUZMdUyXbrJQZjF3Z"
FINNHUB = "d1u11qhr01qt0evdka8gd1u11qhr01qt0evdka90"
TWELVEDATA = "19accad40eee47169a6d8d3c78fb9035"
Financial_Modeling_Prep = "vK2KvGrtG9S4ff89dw8nJB0gNwWZdxGO"
MARKETSTACK = "3c94a725acfacef9ce534d3e9e2780f5"
COINGECKO   = "CG-mxLEWcBCe1TtCxZvXnmcbArN"